# This build script is licensed under CC0 1.0 Universal:
# https://creativecommons.org/publicdomain/zero/1.0/

jobs:
  - job: build
    pool:
      vmImage: macOS-10.13
    timeoutInMinutes: 0
    variables:
      build_name: calinou
      build_threads: "3"
      scons_flags: '("progress=no" "debug_symbols=no" "-j$BUILD_THREADS")'
      godot_repo_url: https://github.com/arrkiin/godot
      godot_repo_branch: module_build
    strategy:
      matrix:
        osx_editor:
          platform: osx
          target: editor
        osx_templates:
          platform: osx
          target: templates
        ios_templates:
          platform: iphone
          target: templates
    steps:
      - script: |
          scripts/azure-pipelines/before_script.sh
          cd "godot/"

          if [[ "$PLATFORM" == "osx" ]] && [[ "$TARGET" == "editor" ]]; then
            ../scripts/azure-pipelines/build/osx_editor.sh
          fi
          if [[ "$PLATFORM" == "osx" ]] && [[ "$TARGET" == "templates" ]]; then
            ../scripts/azure-pipelines/build/osx_templates.sh
          fi
          if [[ "$PLATFORM" == "iphone" ]]; then
            ../scripts/azure-pipelines/build/iphone.sh
          fi
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: $(Build.ArtifactStagingDirectory)
          artifactName: godot

  - job: deploy
    dependsOn: build
    condition: >-
      and(
        eq(variables['Build.SourceBranchName'], 'master'),
        ne(variables['Build.Reason'], 'PullRequest')
      )
    pool:
      vmImage: macOS-10.13
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          downloadType: single
          artifactName: godot
          downloadPath: $(System.ArtifactsDirectory)
